#-------------------------------
# General Site Settings
title: Living Library 3D
logo:
description: Documenting life on earth for sustainable science.
baseurl: "/website" # The subpath of your site, e.g. /blog
url: "https://johnsonlm-website.github.io" # The base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author:
  name: Living Library 3D
  avatar:

# Hero Settings
hero:
  title: Welcome to Living Library 3D
  description: Documenting life on earth for sustainable science.
  image: '/images/hero.jpg'

# Contact Settings
contact:
  email: johnson@johnsonlm.com # Add your email for contant form
  description: Contact us here!

# Footer section
# Example of adding a new link to the footer - {icon: "ion-logo-github", link: "https://github.com"}
# Other icons can be found at https://ionicons.com
social:
- {icon: "ion-logo-twitter", link: "https://twitter.com"}
- {icon: "ion-logo-facebook", link: "https://facebook.com"}
- {icon: "ion-logo-instagram", link: "https://instagram.com"}
- {icon: "ion-logo-github", link: "https://github.com"}


# Comment Section (Disqus)
#disqus-identifier: mr-brown # Add your shortname for Disqus Comment. For example mr-brown

# Google Analytics
#google-analytics: # Add your identifier. For example UA-99631805-1.

# Newsletter
#mailchimp: true # To enable the mailchimp form, use the value true. To turn off use the value false.
#mailchimp-identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

paginate: 9
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed
